language: objective-c
xcode_project: CleanroomAppSettings.xcodeproj
osx_image: xcode8

git:
  depth: 1
  submodules: false

before_install:
  - git submodule update --init

install:
  - gem install xcpretty

script:
- set -o pipefail && xcodebuild -project CleanroomAppSettings.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomAppSettings-iOS -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6s Plus' -destination-timeout 300 clean build | tee "CleanroomAppSettings-iOS-build.log" | xcpretty
- set -o pipefail && xcodebuild -project CleanroomAppSettings.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomAppSettings-iOS -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6s Plus' -destination-timeout 300 test | tee "CleanroomAppSettings-iOS-test.log" | xcpretty
- set -o pipefail && xcodebuild -project CleanroomAppSettings.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomAppSettings-OSX -destination 'platform=macOS' -destination-timeout 300 clean build | tee "CleanroomAppSettings-macOS-build.log" | xcpretty
- set -o pipefail && xcodebuild -project CleanroomAppSettings.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomAppSettings-OSX -destination 'platform=macOS' -destination-timeout 300 test | tee "CleanroomAppSettings-macOS-test.log" | xcpretty
- set -o pipefail && xcodebuild -project CleanroomAppSettings.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomAppSettings-tvOS -destination 'platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p' -destination-timeout 300 clean build | tee "CleanroomAppSettings-tvOS-build.log" | xcpretty
- set -o pipefail && xcodebuild -project CleanroomAppSettings.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomAppSettings-tvOS -destination 'platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p' -destination-timeout 300 test | tee "CleanroomAppSettings-tvOS-test.log" | xcpretty
- set -o pipefail && xcodebuild -project CleanroomAppSettings.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomAppSettings-watchOS -destination 'platform=watchOS Simulator,OS=3.0,name=Apple Watch - 42mm' -destination-timeout 300 clean build | tee "CleanroomAppSettings-watchOS-build.log" | xcpretty

after_failure:
- echo "Travis test result is "
- printf "\niOS build log:\n"
- cat "CleanroomAppSettings-iOS-build.log"
- printf "\niOS test log:\n"
- cat "CleanroomAppSettings-iOS-test.log"
- printf "\nmacOS build log:\n"
- cat "CleanroomAppSettings-macOS-build.log"
- printf "\nmacOS test log:\n"
- cat "CleanroomAppSettings-macOS-test.log"
- printf "\ntvOS build log:\n"
- cat "CleanroomAppSettings-tvOS-build.log"
- printf "\ntvOS test log:\n"
- cat "CleanroomAppSettings-tvOS-test.log"
- printf "\nwatchOS build log:\n"
- cat "CleanroomAppSettings-watchOS-build.log"
